# Generated by Django 5.2.17 on 2026-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'musician',
            },
        ),
    ]
