# Generated by Django 5.2.17 on 2026-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('typeofmusic', models.CharField(max_length=100)),
                ('numberofmembers', models.IntegerField()),
            ],
            options={
                'db_table': 'band',
            },
        ),
    ]
